### ISSUE TITLE
Feature request - multiple selections

### ISSUE THREAD

**Issue by EricRollei** [chrisgoringe/cg-image-picker#1]
Hi, I'm using your image chooser nodes and they work great, thank you for them.   I have a long workflow with a multi-sample, then face and hand detailer and a lengthy upscale after so this saves a bunch of time.    I only wish that I could choose more than one image to pass along.  Ideally, I could make a multi-selection, but even if I could come back to the Image Chooser after completion and make another selection and hit go a 2nd or third time?   This way I could run a batch of say 6 or 8, choose 1,2 or 3 and then let them run.

**Comment by chrisgoringe** [comment]
One option is to make sure that everything upstream of the chooser is fixed (control_after_generate fixed) so that the same result gets fed to the chooser node each time. Then you can rerun the workflow and make a different selection, and the upstream stuff won't be repeated (love this fact about ComfyUI!).

If for some reason that doesn't solve the problem, let me know (maybe post the workflow) and I'll look at multi-selection. Should be possible, but I don't want to make the UI too complicated.

What's the largest number of images you think you'd ever want to choose between? 8?

**Comment by EricRollei** [comment]
Here's the link to the Fabric nodes:   https://github.com/ssitu/ComfyUI_fabric
I could be mistaken but it seems that integrating your chooser with Fabric might be an interesting way to streamline model personalization.    
On a different but related topic - can you use two or more chooser sets inside a workflow?  I don't have a use case other than maybe Fabric, but I'm curious if it's possible - for example in a 2 sampling stage workflow or maybe XY testing?

**Comment by chrisgoringe** [comment]
Yes, you can use two or more chooser sets (in the latest update, anyway).

The value of multi-select is noted :)

Batch size maximum is more a UI thing; you kind of have to create the UI component before you know how many inputs are coming! But I'll think about it!

Looking at Fabric... ah.... creating a new issue, this could be so cool...

https://github.com/chrisgoringe/cg-image-picker/issues/5

**Comment by chrisgoringe** [comment]
So if you update to the latest version, there's a new node in utilities/control/_testing called the Multi Latent Chooser.

It has two text fields, positive and negative, which can take comma separated lists of integers for the 'good' and 'bad' images. Then there are two outputs, one for a batch of all the positive ones, and one for a batch of all the negative ones.

To stop stuff breaking downstream, if either field is empty (no 'good' or no 'bad' images), a single latent of all zeroes is output.

There's also an option to `Discard Previous` or `Accumulate`. Normal behaviour is `Discard Previous`, but if you `Accumulate` then the selected good and bad latents from the previous run will be retained, and you can add more to them. Seems this might help with Fabric...

Let me know how you go!

**Comment by EricRollei** [comment]
Thanks! That was fast work!   I'll try it out sometime this weekend!

**Comment by EricRollei** [comment]
Hey Chris,
Trying this now with a simple iterative Fabric workflow.   It runs, but I'm getting an error after the first selection.  I'm not sure I have the new multi-latent or the fabric stuff wired correctly.   I'm attaching the workflow in a zip for you, and a couple screen grabs. 

 Here's the error from console:

got prompt
3
3
[FABRIC] No reference latents found. Defaulting to regular KSampler.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:14<00:00,  1.37it/s]
[FABRIC] 2 positive latents, 1 negative latents
loading new
unload clone 1
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "A:\Comfy_Aug\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI_fabric\nodes.py", line 181, in sample
    return KSamplerFABRICAdv().sample(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI_fabric\nodes.py", line 138, in sample
    return fabric_sample(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI_fabric\fabric\fabric.py", line 52, in fabric_sample
    samples = KSamplerAdvanced().sample(model_patched, add_noise, noise_seed, steps, cfg, sampler_name, scheduler, positive,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\nodes.py", line 1270, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\nodes.py", line 1206, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\sample.py", line 97, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 120, in KSampler_sample
    return _KSampler_sample(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\samplers.py", line 785, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler(), sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 128, in sample
    return _sample(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\samplers.py", line 690, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\samplers.py", line 630, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\k_diffusion\sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\samplers.py", line 323, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\k_diffusion\external.py", line 125, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\k_diffusion\external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 849, in apply_model
    out = super().apply_model(x, timestep, cc, uu, cond_scale, cond_concat, model_options, seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\samplers.py", line 311, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\samplers.py", line 289, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\samplers.py", line 263, in calc_cond_uncond_batch
    output = model_options['model_function_wrapper'](model_function, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI_fabric\fabric\fabric.py", line 272, in unet_wrapper
    _ = model_func(batch_latents, batch_ts, **c_null_dict)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
                                                                 ^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\ComfyUI_smZNodes\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\model_base.py", line 63, in apply_model
    return self.diffusion_model(xc, t, context=context, y=c_adm, control=control, transformer_options=transformer_options).float()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 70, in new_unet_forward
    x0 = old_unet_forward(self, x, timesteps, context, y, control, transformer_options, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\Comfy_Aug\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 621, in forward
    assert y.shape[0] == x.shape[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^


![image](https://github.com/chrisgoringe/cg-image-picker/assets/97568200/0bd6cf57-3561-4c0b-a724-9ca769f5dd85)

![image](https://github.com/chrisgoringe/cg-image-picker/assets/97568200/9e84b32a-384a-484b-9bef-09bf3dcb63c8)


[iterative-fabric-chooser-multi-latent.zip](https://github.com/chrisgoringe/cg-image-picker/files/12776256/iterative-fabric-chooser-multi-latent.zip)

**Comment by EricRollei** [comment]
In the Fabric demo workflow they use Latent from Batch nodes, but I don't know how to do this or if it's still needed with the Multi Latent Chooser.     Especially if I choose more than one image for pos or neg.  because then the latent from batch #s will be off.

**Comment by chrisgoringe** [comment]
I haven't got Fabric working at all yet, so this is definitely experimental. I'll try the workflow you added!

**Comment by chrisgoringe** [comment]
OK - so look at this workflow fragment:
![image](https://github.com/chrisgoringe/cg-image-picker/assets/4371971/0fbfd5ac-9f51-424c-8341-969c2b58e2f6)
I'm sending two copies of the same latent out of positive, and one out of negative. Then at the bottom, I'm using  FABRICs batch latent. The results are all identical. 

So I think that means that the latent batches are coming out in the right tensor shape.

**Comment by chrisgoringe** [comment]
Got it working! 

I'm using the Use Everywhere custom nodes - https://github.com/chrisgoringe/cg-use-everywhere or search chrisgoringe in ComfyUI Manager - to reduce all the spaghetti - UE nodes broadcast data to unconnected inputs that match...

Here's the workflow:

![image](https://github.com/chrisgoringe/cg-image-picker/assets/4371971/3bdd1108-efd8-45c0-a9f2-5b35685873bb)

I'm just doing two images per batch [edit - four], and picking likes and dislikes - and using the Accumulate option, so I can pile up the ones I like and dislike from each batch. On my 12GB card I've gone up to 4 in the good batch and 7 in the bad without OOM (running a batch in the second step is problematic, though).

Here's the workflow - LMK if it makes sense for you...
[workflow.zip](https://github.com/chrisgoringe/cg-image-picker/files/12777226/workflow.zip)

**Comment by EricRollei** [comment]
Ah cool, I'll see if I can do that first without the UE nodes.          I'm visual...  I need to see the wires to understand the workflow. What happens to existing workflows? Do they load with wires or convert automatically to UE when I have the UE custom nodes enabled?

**Comment by chrisgoringe** [comment]
UE does nothing to existing workflows, it only does anything when you add UE nodes and hook them up. Think of UE nodes as radio transmitters :)

**Comment by EricRollei** [comment]
okay, well, I installed UE, but then I get this message on loading your workflow

![image](https://github.com/chrisgoringe/cg-image-picker/assets/97568200/ab738184-0ae0-4242-aa98-9f5134c8e87c)

**Comment by chrisgoringe** [comment]
Ah - it's because one of the UE nodes was connected to another custom node that you don't have. That's a bad error message, I'll fix: but for now here's a workflow that should work (tested on a clean install with just Fabric, Image Picker, and UE.

[workflow.zip](https://github.com/chrisgoringe/cg-image-picker/files/12779592/workflow.zip)

**Comment by EricRollei** [comment]
Sorry, I missed your new workflow but I managed to get it working on my own with the UE nodes.    It's the first time I have tried iterative fabric, but honestly, I think it's like it's working backwards at least in my workflow since each round the images got farther away from what I wanted.  Here's what I had put together - realized I just needed to double the prompt text encode and but otherwise like your first one with 4 rounds.

[Fabric-4-round-iterative-UEnodes.zip](https://github.com/chrisgoringe/cg-image-picker/files/12780034/Fabric-4-round-iterative-UEnodes.zip)

**Comment by EricRollei** [comment]
I've played with this more and confirmed that Fabric doesn't work with more than one latent feedback per pos or neg.   So I wrote to them on an issue.  But I guess it works fine with exactly one pos and one neg for SD 1.5.    SDXL not working.

**Comment by chrisgoringe** [comment]
OK - I'm going to close this issue then; any new thoughts or ideas, feel free to open a new one.
