### ISSUE TITLE
Select image directly in the preview

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-image-picker#10]
Right-click the image in the preview for image chooser?

**Comment by chrisgoringe** [comment]
Done in 2.2

**Comment by Erehr** [comment]
Can this be expanded especially now with multi latent chooser being an option? (And I'm guessing multi choice will come to normal non fabric image/latent chooser later?). 

Something like windows explorer selection, ctrl + mouse click (maybe even ctrl + left click for positive and right click for negative for fabric) to highlight the images with border/background/icon or even all 3. 
![image](https://github.com/chrisgoringe/cg-image-picker/assets/13292573/6b8d6848-a9c5-4082-a8ff-f24a2230c186)

**Comment by chrisgoringe** [comment]
love that UI mockup! Created a new issue #27 with some details, linking to this.

**Comment by Erehr** [comment]
For that matter with preview node now having both latent and image input/output are the seaprate choser nodes even necessary? How about single node and another for fabric?
![image](https://github.com/chrisgoringe/cg-image-picker/assets/13292573/4cf3603b-ef51-4f11-a45e-b1d8cd51c2bf)
