### ISSUE TITLE
[FEATURE REQUEST] Support for Impact's SEGS

### ISSUE THREAD

**Issue by alessandroperilli** [chrisgoringe/cg-image-picker#101]
Chris, thanks for sharing with the community this great node suite. I added it to the [AP Workflow for ComfyUI](https://perilli.com/ai/comfyui/) long ago and users are very happy with it.

I'm writing to see if you would consider adding support for Impact's SEGS as inputs, on top of images.

A number of Impact's nodes already allow you to automatically choose certain SEGS based on thresholds or other discriminants.
For example, in this example from APW, I can automatically choose to process only certain SEGS that equal to faces of a small size:

<img width="1129" alt="Screenshot 2024-04-23 at 14 40 57" src="https://github.com/chrisgoringe/cg-image-picker/assets/9775949/f644cb49-253b-4e8c-b981-82a35eb4419a">

While this is wonderful to process a large number of images at industrial scale, there are situations where I'd like to manually choose which SEGS (in this example, representing faces) should move forward in the pipeline and which ones shouldn't.

Your Preview Chooser node seems perfect for the job, but it doesn't support SEGS as inputs. Is there any chance you could add this support?

(in the screenshot, for example, I would place the Preview Chooser between node #515 and #546)

Thanks for considering the idea!

**Comment by chrisgoringe** [comment]
Taken me a while to look at this!

@alessandroperilli , are you happy to try a version on a branch? It's very basic at the moment, but it is working.

If you go into the cg-image-picker subdirectory and do
```
git pull
git switch segs
```
then restart comfy. Here's a basic workflow illustrating it...

[segs-workflow.json](https://github.com/user-attachments/files/16244589/segs-workflow.json)

The way it works is to use the SEGSPreview node, plug it's output image list and the segs into the chooser, and then just take the segs output from the chooser.

**Comment by alessandroperilli** [comment]
Hey @chrisgoringe, somehow I missed this reply for three months. I am so sorry! 
I just tried the feature and it works wonderfully. Thank you!
