### ISSUE TITLE
[FEATURE REQUEST] Support API for image picker

### ISSUE THREAD

**Issue by Arthur-xu** [chrisgoringe/cg-image-picker#112]
Hi Chris, thank you for clarification [here](https://github.com/comfyanonymous/ComfyUI/issues/951#issuecomment-2178990178). I'm wondering is it possible to implement this feature in cg-image-picker?

Currently, we're using comfyui api to process workflow, including this image chooser. But seems like cg-image-picker doesn't support API as of now.

**Comment by chrisgoringe** [comment]
I've not used the API, so I'll need to work through this with you. I think all the pieces are there...

When the chooser executes, it sends a message (see line 77 of image_chooser_preview.py) with type `early-image-handler`, and a dictionary of the id, and a list of images in the same format as the built in preview node. Hopefully your client can listen for that message and retrieve the images.

The node then waits for you to send a message back. This is done by a POST to `/image_chooser_message`, with the node `id` (or -1, meaning any/all) and a str `message` which can be:

- a comma separated list of the images to progress (zero indexed), or
- `__cancel__` to terminate the run (no good images

You can also send `__start__` at the start of a run, which clears the message queue

**Comment by chrisgoringe** [comment]
Closing this since there was no response - feel free to reopen or ask me to!
