### ISSUE TITLE
Batch Backlog

### ISSUE THREAD

**Issue by siliconecomputervision** [chrisgoringe/cg-image-picker#117]
It would be amazing if there was functionality to just endlessly run the workflow up to the image-chooser, and then perform a selection from the backlog (perhaps leveraging the temp folder?) to choose many at once

**Comment by chrisgoringe** [comment]
I think that's probably an idea for a different node!

Not totally clear how it's better than saving all the images, looking at them in your operating system, then using one of the nodes that iterates over a folder to reload them into another workflow?

**Comment by siliconecomputervision** [comment]
maybe it's not better but from my perspective it seemed like a natural extension of what your node offers (which is now broken btw)

**Comment by chrisgoringe** [comment]
Thanks, will think. 

Just updated with a fix I think
