### ISSUE TITLE
add lama cleaner to this image chooser node would be a great idea

### ISSUE THREAD

**Issue by huanggou666** [chrisgoringe/cg-image-picker#120]
choose an image and then do the lama cleaning and then pass it on to the left workflow, 

this is the lama-remover node , combine you two together ,https://github.com/Layer-norm/comfyui-lama-remover 
![image](https://github.com/user-attachments/assets/9300e176-996d-428c-a4ee-416c99b76c88)

**Comment by huanggou666** [comment]
![image](https://github.com/user-attachments/assets/b07fcf57-d684-43f0-8929-707f8a2df9dc)
if there is a mask out , I can do lama clean after image chooser

**Comment by chrisgoringe** [comment]
Just checking I understand - this would mean that you create a mask in the image chooser (like you do in the load image node)? And then output that mask as well as the image?

**Comment by huanggou666** [comment]
> Just checking I understand - this would mean that you create a mask in the image chooser (like you do in the load image node)? And then output that mask as well as the image?
<img width="1230" alt="Snipaste_2024-09-16_13-54-02" src="https://github.com/user-attachments/assets/1ff28fce-addf-449d-bdc9-0ea9ee21ca95">


yes just like this shown on this image , this would work fine with one image in image chooser, I don't know how it would work if there are multiple images choosen at the same time

**Comment by huanggou666** [comment]
![image](https://github.com/user-attachments/assets/622b8348-bfd3-467e-b5e5-ae1cb30e271f)
just tested,you can only paint mask for the first image in image chooser ,if there are multiple images in image chooser, 
it would be great ,if  I can choose any image  just one,then paint a mask ,then pass this image and it's mask to the lama cleaner,

**Comment by chrisgoringe** [comment]
Right. Unfortunately the way the Image Chooser is done, and the way the mask editor is done, makes this tricky....

I'll think about it - but I suspect a completely different node would be the solution (one that just takes one image and lets you create a mask)

**Comment by huanggou666** [comment]
> Right. Unfortunately the way the Image Chooser is done, and the way the mask editor is done, makes this tricky....
> 
> I'll think about it - but I suspect a completely different node would be the solution (one that just takes one image and lets you create a mask)

I seem can't find other node that can pause in the middle of workflow to let you paint the mask of the output image then pass it on.

**Comment by chrisgoringe** [comment]
No, I don't know of one. I mean I think it would be easier to write one than to adapt Image Picker! I will give it some thought,

**Comment by huanggou666** [comment]
> No, I don't know of one. I mean I think it would be easier to write one than to adapt Image Picker! I will give it some thought,

great ,thank you , I think people would like this kind node
