### ISSUE TITLE
Ive been using this for along time and now i get the a problem, 

### ISSUE THREAD

**Issue by trashie65** [chrisgoringe/cg-image-picker#121]
Ive been using this for along time and now i get the same problem, generating a picture the workflow just stops, if you try and start the prompt again it says open in another tab.. and you have to restart comfy server... if you just use a normal preview picture node the workflow works ok?
*** Update*** Just added Preview Chooser to the Default Workflow and you get this error Prompt has no outputs, if i load a previous workflow it works ok if you add it to a new workflow it stops working.
![chooser](https://github.com/user-attachments/assets/700c1231-c826-430b-849b-e706d9549838)

_Originally posted by @trashie65 in https://github.com/chrisgoringe/cg-image-picker/issues/119#issuecomment-2352048631_

**Comment by chrisgoringe** [comment]
The image picker mode isn't an output. It should always have something downstream of it. Put an image preview or save after it.

If there are problems with a different workflow, please post them separately.
