### ISSUE TITLE
not working anymore after comfyui 2024/11/23 update

### ISSUE THREAD

**Issue by huanggou666** [chrisgoringe/cg-image-picker#125]
not working anymore after comfyui 2024/11/23 update
![image](https://github.com/user-attachments/assets/39e506d3-e19e-4d2a-8b85-d601b81131b3)

**Comment by chrisgoringe** [comment]
could you press f12 and see if there are any errors in the javascript console?

**Comment by huanggou666** [comment]
> could you press f12 and see if there are any errors in the javascript console?

https://github.com/user-attachments/assets/0ca3215e-ae77-41da-a1c0-b07a569b5b30

![image](https://github.com/user-attachments/assets/d501fb26-8d9f-4582-9c15-906a44817ddc)

![image](https://github.com/user-attachments/assets/143f495e-83e3-4dac-99ef-1eef91715fb4)

**Comment by chrisgoringe** [comment]
thanks, I will investigate

**Comment by chrisgoringe** [comment]
I have it working with the latest Comfy. Is your image-picker up to date? It should be 2.15. See the `__init__.py` file - last line:

```python
IP_VERSION = "2.15"
```

If not you can manually update

```sh
cd custom_nodes/cg-image-picker
git pull
```

**Comment by huanggou666** [comment]
> I have it working with the latest Comfy. Is your image-picker up to date? It should be 2.15. See the `__init__.py` file - last line:
> 
> ```python
> IP_VERSION = "2.15"
> ```
> 
> If not you can manually update
> 
> ```shell
> cd custom_nodes/cg-image-picker
> git pull
> ```

I updated comfyui-easy-use node,now it works
