### ISSUE TITLE
Possible Issues:  Cueing another batch causes the Chooser to select the 1st image

### ISSUE THREAD

**Issue by EricRollei** [chrisgoringe/cg-image-picker#2]
I'm using Chrome with the standalone ComfyUI install recently updated.
The problem seems to be if I cue another set of batches while the first one is still running, the chooser will select the 1st image in the set without waiting for the user to choose. Possibly just with my set up so maybe only on my side?

**Comment by chrisgoringe** [comment]
Could you post the workflow? I'd like to work this out.

**Comment by EricRollei** [comment]
I've been trying to replicate this behavior after restarting chrome.  I can't seem to get it to happen again.   I think you can close this one.

**Comment by chrisgoringe** [comment]
Thanks. If you do reproduce, please open a new issue and post the workflow and details.
