### ISSUE TITLE
Warning when nodes aren't paired nicely

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-image-picker#29]
Chooser nodes should always be directly downstream of a preview and fully connected: that way they can be closely integrated.

Should warn if this isn't the case (maybe even refuse to run?)

**Comment by chrisgoringe** [comment]
Make inputs required on choosers?

Could make the outputs of 'preview' custom types which will only connect to the inputs of the chooser.

**Comment by Erehr** [comment]
Is there a reason for not making it a single node? And maybe another just for Fabric? Something like
![image](https://github.com/chrisgoringe/cg-image-picker/assets/13292573/30dca410-0f48-4856-8732-18a719c23a50)

![image](https://github.com/chrisgoringe/cg-image-picker/assets/13292573/2d90e8e5-673b-454d-8928-6f808cc05ae6)

**Comment by chrisgoringe** [comment]
Yes, there is a reason for having two nodes... The images are only available at the end of the node execution - they are part of the output.

So you can't see the images and then determine the output of the same node. Hence the need to have two linked nodes...

**Comment by chrisgoringe** [comment]
Hmmm. Maybe....

if I added a custom event listener to the api:

```javascript
import { api } from "../../scripts/api.js";

function earlyImageHandler(event) {
	try {
		let nodes = app.graph._nodes_by_id;
		let node = nodes[event.detail.node_id];

		if(!node) {
			console.log(`invalid node id '${event.detail.node_id}'`);
			return;
		}

		// do something with event.details.urls
		
	}
	catch(e) {
		console.log(`exception occurs\n${e}`);
	}
}

api.addEventListener("early-image-handler", earlyImageHandler);
```

then I think 
```python
PromptServer.instance.send_sync("early-image-handler", {"node_id": unique_id, "urls":[preview1, preview2, ...]})
//now wait
```
could send the images in mid-execution...

**Comment by chrisgoringe** [comment]
Done in new branch
