### ISSUE TITLE
invalid literal for int() with base 10: 'Always pause'

### ISSUE THREAD

**Issue by IdeaFridge** [chrisgoringe/cg-image-picker#31]
![image](https://github.com/chrisgoringe/cg-image-picker/assets/145101935/6613439b-c894-4851-8c47-54fd8ad85ec8)

(Every extensions/comfyui is up to date.) 
The same thing happens when I use 'latent chooser'.

By the way, thanks for your effort! This custom node really helps my workflow!  (if it works) 

--Edit

If I change 
i = (int(MessageHolder.waitForMessage(id))-1) % images.shape[0]
to just 
i = 2 % images.shape[0]  
then it works, but of course I can't choose the image index  I want to use.

**Comment by chrisgoringe** [comment]
I think this is due to some old code hanging around - could you stop comfy, go into comfy/web/extensions and remove anything which looks like it's part of image chooser ? Either directly in that folder, or under cg-nodes?

Then restart.

It's safe to remove anything except 'core' in the web/extensions directory; everything else gets installed by comfy at start time.

I'll automate this in the next release.

**Comment by IdeaFridge** [comment]
> I think this is due to some old code hanging around - could you stop comfy, go into comfy/web/extensions and remove anything which looks like it's part of image chooser ? Either directly in that folder, or under cg-nodes? Just be sure not to remove the folder called 'core'
> 
> Then restart.
> 
> It's safe to remove anything except 'core' in the web/extensions directory; everything else gets installed by comfy at start time.
> 
> I'll automate this in the next release.

thanks! now it works.

but after uninstalling cg-nodes, a new error below appears. 

![image](https://github.com/chrisgoringe/cg-image-picker/assets/145101935/3cb73103-3f38-4346-8844-2c9c4a1f2d6d)


I reinstalled use-everywhere custom node but no pregression :(

**Comment by chrisgoringe** [comment]
OK - that's due to an incompatibility of the rgthree nodes with the latest version of comfy - see the thread [here](https://www.reddit.com/r/comfyui/comments/171x2ku/suggest_reverting_comfyui_back_to_4103f7f_if_you/)

**Comment by IdeaFridge** [comment]
> OK - that's due to an incompatibility of the rgthree nodes with the latest version of comfy - see the thread [here](https://www.reddit.com/r/comfyui/comments/171x2ku/suggest_reverting_comfyui_back_to_4103f7f_if_you/)

My sincere appreciation. You saved me 👍
