### ISSUE TITLE
Issue with chained choosers (edit: when used with Context node from rgthree-comfy)

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-image-picker#32]
https://reddit.com/r/comfyui/s/hEMQtJJjto

**Comment by chrisgoringe** [comment]
Fixed in new nodes

**Comment by Erehr** [comment]
One more bug with chained choosers where restart will always trigger first chooser. 

Choose from 1st one -> Choose from 2nd one -> finish -> restart from 2nd -> now 1st one is waiting for selection

**Comment by chrisgoringe** [comment]
I can't reproduce - this workflow seems to work as it ought to 

- run
- select two images in chooser 1
- progress them
- select one of them in chooser 2
- progress it
- select the other one in chooser 2
- progress as restart

[workflow-chain.zip](https://github.com/chrisgoringe/cg-image-picker/files/12862394/workflow-chain.zip)

If you have an example of it not working, could you share the workflow?

**Comment by Erehr** [comment]
Couldn't reproduce it with simple workflow either, so I slowly simplifying my current one to see at which point it will work and what may cause it. Seems to be the issue with Context node from [rgthree-comfy](https://github.com/rgthree/rgthree-comfy). Replaced it combination of 'Pipe In / Pipe out' from other extensions and it's working. Have to keep workflow organized somehow (UE Nodes wink* wink*)
![image](https://github.com/chrisgoringe/cg-image-picker/assets/13292573/63700230-bbe4-4d19-b1d1-48d96f7ca2a8)

**Comment by chrisgoringe** [comment]
That's not a big surprise - rgthree nodes (which I love, btw) hijack the graphPrompt in the same way that restart does.

But if you were to share a simple-as-possible workflow that *fails* I could look at whether they can be made to play nice.

**Comment by Erehr** [comment]
https://gist.github.com/Erehr/3d13a20a3f797fa4a1098e8704b75457

Restarting from second chooser will run sampler again with the same result (even with randomized seed)

**Comment by chrisgoringe** [comment]
Need to check if this is still a problem with the changes in latest versions

**Comment by chrisgoringe** [comment]
OK, this is actually expected behavior...  

Why? When you restart at chooser 2, we need to work out what nodes are still needed. So we head downstream, finding everywhere the data from the restart will go. So that's nodes with id (14, 16, 17, 8).

But then each of those nodes needs it's inputs. So we go back upstream to work out what's needed. But node 17 gets its VAE from the rightmost context node (19), so that has to run, and it gets data from the middle context node (15), so that has to run, and it gets data from the left hand context node (18) and from (13), so 18 and 13 have to run etc. In fact, everything needs to run!

It should be possible to fix with UE like this (21 connected back to 1)
![image](https://github.com/chrisgoringe/cg-image-picker/assets/4371971/c31e612c-95d9-4a61-9bfe-cc9b6d6fe7f2)
but at the moment restart doesn't know about UE links - that's issue #26 and I plan to fix it soon!

This (with the reroute connected back to 1) does work:
![image](https://github.com/chrisgoringe/cg-image-picker/assets/4371971/7f5d11d2-68e2-4b3e-bb95-e52604eec33c)


So - closing this, but watch #26 for news!

**Comment by chrisgoringe** [comment]
OK - update both image chooser and UE, and this now works:

[workflow-works.zip](https://github.com/chrisgoringe/cg-image-picker/files/12903427/workflow-works.zip)

(note I had to connect the latent input to the first chooser node... ALWAYS connect the latents!
![image](https://github.com/chrisgoringe/cg-image-picker/assets/4371971/c476fd04-15f7-4a87-9e28-a3b46d323bbb)
