### ISSUE TITLE
Error After Update

### ISSUE THREAD

**Issue by trashie65** [chrisgoringe/cg-image-picker#34]
Hi After updating today i now get this error

![image error](https://github.com/chrisgoringe/cg-image-picker/assets/45748708/77244a8f-a79f-4e51-9825-ddda0103bd7f)

Also from the comfy log:

File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker\image_chooser.py", line 87, in func
    i = (int(MessageHolder.waitForMessage(id))-1) % images.shape[0]
ValueError: invalid literal for int() with base 10: 'Always pause'

I too have the issue that i have no right click option and also the floating cancel box is not showing?

**Comment by chrisgoringe** [comment]
Can you try deleting the chooser node and creating a new one? And if it's still a problem, could you post a screenshot of the relevant nodes in your workflow?

**Comment by trashie65** [comment]
Ive already deleted and added another one.. you want a screen shot of all the nodes?

**Comment by chrisgoringe** [comment]
Mostly just the chooser node - the problem here is that it is sending the value of the mode widget ('Always pause') when it should be sending the choice...

**Comment by chrisgoringe** [comment]
Also, pls check if there are any relevant looking things in the javascript console

**Comment by trashie65** [comment]
![image error2](https://github.com/chrisgoringe/cg-image-picker/assets/45748708/306a1d39-77d8-45b1-9915-02ccfd4a8cbe)

Where is the javascript console?

**Comment by trashie65** [comment]
if its F12 then im looking now

**Comment by chrisgoringe** [comment]
Attached here is a very simple workflow that is currently working on my install. Could you see if it works on yours? That will really help to narrow this bug down! 

[workflow.zip](https://github.com/chrisgoringe/cg-image-picker/files/12842765/workflow.zip)

**Comment by trashie65** [comment]
![image error3](https://github.com/chrisgoringe/cg-image-picker/assets/45748708/a1788440-a137-45eb-8c07-9f8dd69697bb)

**Comment by trashie65** [comment]
The weird thing is apart from the floating canel box and the right clicking to choose the image, the rest was working befor the update?

**Comment by trashie65** [comment]
Do we have any update on the bug finding? at the moment i am using a previous version which is working ok... except for the floating cancel and the right click option?

**Comment by chrisgoringe** [comment]
Take a look at the new branch mentioned towards the end of this thread

https://github.com/chrisgoringe/cg-image-picker/issues/33

I'm probably not going to fix issues in the old nodes, the new one is so much cleaner and more reliable
