### ISSUE TITLE
(Ctrl - )click to select or unselect

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/cg-image-picker#36]

**Comment by chrisgoringe** [comment]
Will look at that. The reason I've currently done it as I have is that adding to the right-click menu is directly supported in ComfyUI, so I think it's a lot less likely to get broken. Similarly the brightness is done deep in the ComfyUI code....

So I only plan to change those things if I can find a safe place to hijack the code!

**Comment by Erehr** [comment]
Love it. Except now there's no way to cancel waiting chooser I think. There's no cancel button on hud and chooser (blank button without text) and no cancel under right click menu.

**Comment by Erehr** [comment]
Also probably a bug: Can't cancel there either if the chooser is waiting
![image](https://github.com/chrisgoringe/cg-image-picker/assets/13292573/3bb23e14-4983-45ca-9c83-5837946b0002)

**Comment by chrisgoringe** [comment]
right-click on the background canvas?

**Comment by chrisgoringe** [comment]
> Also probably a bug: Can't cancel there either if the chooser is waiting ![image](https://user-images.githubusercontent.com/13292573/274897499-ea126bf4-3ce3-4f30-a3e2-65ef177b8489.png)

Added #40

**Comment by chrisgoringe** [comment]
> Love it. ❤️ Except now there's no way to cancel waiting chooser I think. There's no cancel button on hud and chooser (blank button without text) and no cancel under right click menu.

added as #41

**Comment by chrisgoringe** [comment]
Fixed - there is now a cancel button on the chooser, and cancel works from the "Running" section
