### ISSUE TITLE
module 'comfy.samplers' has no attribute 'wrap_model'

### ISSUE THREAD

**Issue by ZainHan33** [chrisgoringe/cg-image-picker#49]
I'm testing the workflow you have posted and this is the error I get after choosing 2 images from the first batch

Error occurred when executing KSamplerFABRIC:

module 'comfy.samplers' has no attribute 'wrap_model'

**Comment by chrisgoringe** [comment]
Is comfy up to date?

**Comment by chrisgoringe** [comment]
This is an issue with KSamplerFABRIC, not the image picker
