### ISSUE TITLE
Image refiner halts workflow.

### ISSUE THREAD

**Issue by Strontium99** [chrisgoringe/cg-image-picker#50]
This is a brilliant node, and something I've been after for a long time. My only issue is at the point of the "Preview chooser" I can access the image refiner by right clicking the image, do some inpainting and tweaking. But when I then save to node, the option to continue the workflow has gone. Don't know if it's possible to fix this?

**Comment by chrisgoringe** [comment]
Not familiar with the image refiner... can you post a workflow?

**Comment by Strontium99** [comment]
[a-workflow.json](https://github.com/chrisgoringe/cg-image-picker/files/13040363/a-workflow.json)
Sure thing. To be honest, I'm not too sure where the image refiner came from. It's not a node as such, so don't know if it will show within the workflow, Attached on anyhow. Also attached a couple of screen grabs to show you what I'm on about. 
Hope this help.
![Snap1](https://github.com/chrisgoringe/cg-image-picker/assets/368429/a3b5fdf7-af56-4865-88e9-97df436b1fac)
![Snap3](https://github.com/chrisgoringe/cg-image-picker/assets/368429/724bd666-5d2e-444b-90ca-81a0159df6ad)

**Comment by Erehr** [comment]
Probably from [ComfyUI-Workflow-Component](https://github.com/ltdrdata/ComfyUI-Workflow-Component).

Noticed the same thing but I can't get inpainting to work anyway and forgot to report it.
