### ISSUE TITLE
Feature request - space around images

### ISSUE THREAD

**Issue by EricRollei** [chrisgoringe/cg-image-picker#53]
Thanks for all the hard work you've put in so far.  I'm using the chooser a lot and everything is working smoothly now. This is just a minor thing....

It would be nice to have a little space between the images in the chooser so you can see the boundaries more easily.  When they are all somewhat similar and they are touching side to side, top to bottom they kind of all run together.  This way you could also put the green outline around the outside rather than on the inside of the selected images too if you wanted.

**Comment by chrisgoringe** [comment]
Just got around to doing this :)
