### ISSUE TITLE
Request: Special Case Where Image Selection is Not Possible

### ISSUE THREAD

**Issue by Trobinou** [chrisgoringe/cg-image-picker#55]
Hello,

I have encountered a workflow scenario where the 'Image Chooser' feature does not allow me to select the desired image after a batch operation. Specifically, I am generating multiple images by modifying the noise, but all the images have the same seed. 
This might be the cause of the issue...

To provide better insight, I have shared my workflow with you: https://drive.google.com/file/d/1-M6mTZVeY9QoP6yw5N3rF9z_Z4I3_ua_/view?usp=sharing

Would it be possible to make a modification to your node so that it can work?

Thank you.

**Comment by chrisgoringe** [comment]
Thanks for posting the workflow :). I'm looking at this...

**Comment by chrisgoringe** [comment]
Please update to the new version (2.6.2) and check it works for you now.

**Comment by Trobinou** [comment]
It works perfectly, it's just fantastic! 👍💯 
Thank you very much 🙏
