### ISSUE TITLE
[Feature Request] Discard mode

### ISSUE THREAD

**Issue by noembryo** [chrisgoringe/cg-image-picker#60]
Seeing the #59 I thought of something that it will greatly help my daily routine.
An extra mode. A Discard all (but not pass through) mode.

I don't know if it's already possible with some other configuration, but this is what I do:
I don't work with batches of many images.
I have the preview chooser node before the last Save Image node of my workflow.
Most of the time I try things that I don't want saved, so I always press the "Cancel current run" after I see the output that I'm not satisfied with.
I only want to save the ones I like, so I press the "Progress selected Image" for them.
That's why it will be really helpful if I could have every generation cancelled until I find one that I like to select and press the "Progress selected Image" for it.

BTW nice node. 👍 
Thank you for your work.. 😃

**Comment by chrisgoringe** [comment]
I don't quite understand how this would work. Maybe I haven't understood?

If you set it to discard all, how will you get the images that you do like? Surely you need to decide once you see the image, and either pass it on or not (which you can do with "Cancel Current Run" as you do at the moment)? Note that you can't change the mode once the workflow has started...

When I'm doing what you describe I turn Auto Queue on, then when I cancel it restarts automatically.

**Comment by noembryo** [comment]
Perhaps my explanation wasn't that good.. 
What I'm trying to avoid is the pressing of the Cancel button (that's happening a lot!!).
What I would like, is something that I don't think is possible at the moment.

When the image arrives at the node, it should display itself and always choose the Cancel action.
If I don't like it (like most of the times) I can start a new generation.
But if I like what I see, I want to have the option to select the image and press Progress selected image so that it can be saved.

**Comment by chrisgoringe** [comment]
So does it give you a period of time to decide you do like the image before it dies a cancel and restart?

**Comment by noembryo** [comment]
Actually I was thinking of always Canceling.
The next generation should be manual. Nothing to do with the saving of the image.

**Comment by noembryo** [comment]
Start a generation.
I don't like the outcome.
Start another.
I like this one. Select the image>Press Progress selected
Start another.
Start another.
...

**Comment by chrisgoringe** [comment]
But instead you keep pressing "start"? If you turn on auto queue, cancel effectively does start as well... so one press either way?

**Comment by noembryo** [comment]
Well, yeah, but there is not a keyboard shortcut for Cancel, contrary to the Ctrl+Enter..

**Comment by chrisgoringe** [comment]
I'm imagining another node - one that shows you a single image and you click "yes" or "no". Yes passes it on, No cancels the run and starts another...

**Comment by noembryo** [comment]
If I want to change something in another node, the mouse is away from the preview and I have to go back there and target the cancel button...
This is what I try to avoid.
>I'm imagining another node - one that shows you a single image and you click "yes" or "no". Yes passes it on, No cancels the run and starts another...

Hopefully with a keyboard shortcut? 😉

**Comment by revolvedai** [comment]
Removing the cancel would be great. You would just queue up another set of images from the start and it would progress them through. 

Right now you have to click cancel because the workflow never "Completes" and is always stuck in the queue until you cancel.
