### ISSUE TITLE
Reload old versions of node (was: invalid literal for int() with base 10 Error)

### ISSUE THREAD

**Issue by pixldevjp** [chrisgoringe/cg-image-picker#61]
After updating comfyui yesterday I see the following error when running my workflow.
```
ERROR:root:  - Failed to convert an input value to a INT value: count, , invalid literal for int() with base 10: ''
ERROR:root:* Preview Chooser 49:
```

I have removed the image-picker node from my system and reinstalled it via git clone and also via the comfy manager but the error has not resolved itself.

I'd appreciate any advice or hints for a workaround, as I really do enjoy using the image preview chooser in nearly all of my workflows lately.

Thanks in advance.

**Comment by chrisgoringe** [comment]
Can you try removing the chooser node and re-adding it? 

There's a new widget that's been added, I suspect that's the issue. If that works I can put a proper fix in after the weekend.

**Comment by pixldevjp** [comment]
Chris, thanks for your reply and for your work on this awesome node.

I'm happy to report that removing the node from the workflow and then re-adding it works without any further error.

Much appreciated!!

**Comment by chrisgoringe** [comment]
Changed title to reflect what I need to fix

**Comment by chrisgoringe** [comment]
Reopened just to remind me to do a proper fix

**Comment by MG007Raiser** [comment]
Readding it worked, thanks!

**Comment by chrisgoringe** [comment]
2.7.1
