### ISSUE TITLE
Locks up Comfy if you Reload or Ctrl-Z 

### ISSUE THREAD

**Issue by Immac** [chrisgoringe/cg-image-picker#66]
As the title says, if you for some reason ctrl-z or reload the chooser is active you can't cancel the queue and have to restart comfy. In the case of ctrl-z you can still click the cancel button, it just does not show up, but not if you reload the page.

**Comment by chrisgoringe** [comment]
Thanks for the report. I'm travelling at the moment but I'll definitely look at this when I get back.

**Comment by chrisgoringe** [comment]
Note to self: this is because the Python backend is stuck in waiting mode.

Need to see if there is a signal sent on page reload or similar; alternatively maybe a configurable timeout?

**Comment by chrisgoringe** [comment]
reload fixed in 2.8.2.

ctrl-z doesn't do anything.
