### ISSUE TITLE
Can't open image when there is only one image on the chooser

### ISSUE THREAD

**Issue by Immac** [chrisgoringe/cg-image-picker#68]
![image](https://github.com/chrisgoringe/cg-image-picker/assets/3265190/caab2c09-6b51-459a-8f09-138f9d7d523b)
vs
![image](https://github.com/chrisgoringe/cg-image-picker/assets/3265190/70eb5f57-65de-4e1e-9e21-19fe73ef7f84)

**Comment by chrisgoringe** [comment]
fixed in latest update
