### ISSUE TITLE
"Restart with selected" should override "Take n"

### ISSUE THREAD

**Issue by Immac** [chrisgoringe/cg-image-picker#69]
When the node is in "Take n" mode, if you restart, it'll ignore your choices, 
when the workflow is working automatically "Take n" works fine, but if it's a restart and I'm choosing a set of pictures it's a given that I want the images I chose to be used and not the n images of the "Take n".

**Comment by chrisgoringe** [comment]
Need to know why you are using "take n", I think it's a fairly rare use so I'm unlikely to work on fixing it.

**Comment by Immac** [comment]
> Need to know why you are using "take n", I think it's a fairly rare use so I'm unlikely to work on fixing it.
Usually I use it to take 1 and let it follow the process, but I generate a few more, so if I like another one I can select that one and send it, so my usual workflow is take 1 but sometimes I like another one and want to send it, but I have to change it to bypass because if I don't it just takes the first one again.,

**Comment by Immac** [comment]
> Need to know why you are using "take n", I think it's a fairly rare use so I'm unlikely to work on fixing it.

![image](https://github.com/chrisgoringe/cg-image-picker/assets/3265190/eafe4aa6-b663-454a-8704-e3710a6be531)
![image](https://github.com/chrisgoringe/cg-image-picker/assets/3265190/7c5b9508-7bf1-4835-9109-fb2c2b25b0e8)

Let's say I want to choose between two parts of the process, I by default take the first one, but let's say I want sometimes to use the other picture, click "using selected as re-start" should do exactly that, use the selected ones as a restart, not take the first one again.

**Comment by chrisgoringe** [comment]
OK, that might make sense... I'd be inclined to say run the workflow again with the same seeds, though.

**Comment by Immac** [comment]
> OK, that might make sense... I'd be inclined to say run the workflow again with the same seeds, though.
If the workflow is stochastic you can't guarantee the same picture, also for consistency, the button is "Selected as Restart", not "Do again"
