### ISSUE TITLE
Incompatabilities with frontend

### ISSUE THREAD

**Issue by SampleTexting** [chrisgoringe/cg-image-picker#70]
Doesn't work with [StableSwarmUI](https://github.com/Stability-AI/StableSwarmUI), I'm unsure as to why, but it causes the UI to lock up and glitch, then requires an entire server restart to fix the issue because nothing else can be queued. Also, I'm unable to choose an image within the image picker.

**Comment by chrisgoringe** [comment]
Could you let me know if this is still an issue? There have been a number of changes that might have resolved this, and I don't use StableSwarmUI.

If it is an issue - please look at the javascript console (f12) for errors.

**Comment by SampleTexting** [comment]
Unfortunately it does seem to still be an issue. Here is what my UI looks like: 
![image](https://github.com/chrisgoringe/cg-image-picker/assets/155495184/59a98e73-3599-4fd5-a164-dde0b680282e)

Here is what the console says upon load:
![image](https://github.com/chrisgoringe/cg-image-picker/assets/155495184/6ddb03e6-e6a1-4eb1-8f75-385525d1f73c)

However it seems as though the server lock-up is fixed
