### ISSUE TITLE
Coming from efficient KSampler, getting index errors preventing to continue workflow

### ISSUE THREAD

**Issue by CaptainGrock** [chrisgoringe/cg-image-picker#72]
Hi - this is a very innovative custom node! I am getting consistent errors though right now. I've included the WF but very basically, creating a batch of 3 in efficient KSampler. Routing to Image Chooser, routing the image to VAE Encode and then to a second KSampler. If I choose any image other than the first one (even with the correct index count provided), I get an index out of bounds error. Can you take a look please?

[SampleImageChooser_BUG.json](https://github.com/chrisgoringe/cg-image-picker/files/13911429/SampleImageChooser_BUG.json)

**Comment by chrisgoringe** [comment]
I'm travelling at the moment but I'll take a look when I'm home next week. Does the error occur if you don't use the efficient ksampler?

**Comment by CaptainGrock** [comment]
Hi - sorry for the delay. I tried on the normal KSampler and it was the
same error message. Thanks for taking a look/fixing (looking forward to
feature this in an upcoming video).

Jeff
