### ISSUE TITLE
Feature request: Cancel waiting on next Queue prompt 

### ISSUE THREAD

**Issue by Erehr** [chrisgoringe/cg-image-picker#8]
The plugin is great but I find myself missing one particular feature. 

Let's say I generate 4 images and now they are waiting for upscale and I don't like any of them. 
Like A1111 I want to just click generate (queue prompt) to try again. Here I first have to find image picker node and manually cancel it each time. It would be great if next Queue prompt cancelled that waiting.

**Comment by chrisgoringe** [comment]
I'm not sure that automatically cancelling is good (I find myself clicking 'Queue Prompt' instead of 'go' sometimes!). 

What I might try to do is create some sort of UI element (like a HUD) that appears when the run is paused - it could have a cancel button, and maybe a 'zoom to node' or similar.

**Comment by chrisgoringe** [comment]
The latest version has a basic HUD - when paused, a cancel button floats near the top left of the screen. I've got several ideas to make this more useful. (Pick and go, cancel and restart, to name but two)

**Comment by chrisgoringe** [comment]
done in 2.2 - other aspects separated out
