### ISSUE TITLE
Problems with partial workflow being dumped in output images

### ISSUE THREAD

**Issue by robmacl** [chrisgoringe/cg-image-picker#80]
I've had problems where the dumped workflow in a saved image is missing all of the stuff upstream of the chooser node. I think maybe this happens when I use the restart option. This workflow has two level choosing, and the second doesn't connect the latent input. 
![astro_00023_](https://github.com/chrisgoringe/cg-image-picker/assets/273477/46d1a6d3-f9ac-45d4-bdf8-802b7372e423)
[astro_cathedral_workflow.json](https://github.com/chrisgoringe/cg-image-picker/files/14173314/astro_cathedral_workflow.json)

**Comment by chrisgoringe** [comment]
This is inevitable due to the way that the restart works.
