### ISSUE TITLE
[Feature Request] Output the selected images as a list of integers

### ISSUE THREAD

**Issue by QuackAstra** [chrisgoringe/cg-image-picker#85]
Use case: Image generation with 4 different prompts, Images 1 and 4 get chosen and processed, further refinement follows with prompts 1 and 4

Output example: 1, 4

**Comment by chrisgoringe** [comment]
So this is an additional output - to be consumed by another custom node, I assume?

I would need to be sure of the format the output needs to be in - when you say "list of integers" I'm not sure if you are referring to a 'list' in the Python sense (a variable of type list[int]), or a string with the number comma-separated as you showed it. 

What does the downstream node need?

**Comment by QuackAstra** [comment]
I think a string separated by commas would suffice, this could be split with a "," separator and the string type converted to integers.

**Comment by chrisgoringe** [comment]
> A single integer for the 'Progress first node' mode would also work for all my use cases.

The output needs to be a well defined type, so if it's to be a comma separated list of integers (as a string) that it'll need to be a string always. Will that work?

**Comment by QuackAstra** [comment]
Yes, absolutely!

**Comment by chrisgoringe** [comment]
OK - this is added. Note that we use zero indexing (so the first image is '0', the second is '1' etc)
