### ISSUE TITLE
The HTMLImageElement provided is in the 'broken' state

### ISSUE THREAD

**Issue by scxsyu** [chrisgoringe/cg-image-picker#89]
When running to the preview chooser node, the image is not displayed. As soon as the mouse moves, the browser window freezes, and nothing is displayed on the node. The console throws an error: "Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state." The error occurs at this line of code: "ctx.drawImage(img, imgX+cell_padding, imgY+cell_padding, imgWidth-cell_padding2, imgHeight-cell_padding2);"
I am using the Edge browser.

**Comment by chrisgoringe** [comment]
I can't reproduce this - any other information that might help?

**Comment by scxsyu** [comment]
![image](https://github.com/chrisgoringe/cg-image-picker/assets/97291771/499d4c58-bc04-4c11-9339-897350834c0e)
![image](https://github.com/chrisgoringe/cg-image-picker/assets/97291771/e75d39e2-8a7c-4443-b8fc-ef376c42d6b1)
I have tried switching to Chrome, disabling all browser extensions, disabling all custom_nodes of ComfyUI except manager and picker, but the error still occurs. Now I run the picker in a minimized window and can use it with hotkeys.

**Comment by chrisgoringe** [comment]
I still can't reproduce this. Could you share a workflow - as simple as possible - that has the problem?

Also, are you running the latest Comfy?

**Comment by chrisgoringe** [comment]
@rsl8 opened this as a new issue, since I don't think it's related!

**Comment by chrisgoringe** [comment]
Added #110 to keep the issues cleanly separated
