### ISSUE TITLE
Error occurred when executing LatentBatch

### ISSUE THREAD

**Issue by kakao014** [chrisgoringe/cg-image-picker#93]
Thanks for your great work.

But i Got an error when executing the Fabric Workflow from Example:

Error occurred when executing LatentBatch:
LatentBatch.batch() got an unexpected keyword argument 'latent2'

**Comment by chrisgoringe** [comment]
I'm not going to get to this for a few days - busy time - but I will look at it!

**Comment by chrisgoringe** [comment]
Fabric workflow is now deprecated.
