### ISSUE TITLE
Feature request: configurable shortcuts

### ISSUE THREAD

**Issue by Coding-Kiwi** [chrisgoringe/cg-image-picker#94]
When I modify factors in the prompt and type a number like 1 or 2 it triggers a pick
In mode "progress first pick" this means I have to wait until the upscale is done until I can try the next prompt

would be nice to disable this somehow
thank you for the node!

**Comment by Coding-Kiwi** [comment]
well I could also just hit "cancel run" before modifying the prompt but I'm too stupid to do so xD

**Comment by chrisgoringe** [comment]
Yah, I've been meaning to do this for a while, in order to avoid possible clashes with other nodes as well.
