### ISSUE TITLE
is it possible to merger images to batch for preview chooser?

### ISSUE THREAD

**Issue by K-O-N-B** [chrisgoringe/cg-image-picker#96]
![image](https://github.com/chrisgoringe/cg-image-picker/assets/152141077/0b10375f-734b-4c15-9f41-5ff0be2eb4c4)

I've make the workflow like this, the batch can be see in "prevew image node" but nothing show in "preview chooser node", am I did anything wrong?

btw, could you tell me what the "count" mean?

Thank you~!

**Comment by chrisgoringe** [comment]
You need something downstream of the chooser node; unlike the preview, it
isn’t intended as an endpoint.

**Comment by K-O-N-B** [comment]
worked~! thank u！
