### ISSUE TITLE
[Feature Request] For the modification to support real-time drawing

### ISSUE THREAD

**Issue by RexLeeGrey** [chrisgoringe/cg-image-picker#97]
First of all thank you for this node is very good to use!

There is an idea I don't know if it is troublesome to implement, transform this node of yours into a new node, the new node will not normally pass data or pause the current queue, there is a button on the node that when pressed will allow data to be passed through once, and then continue to remain in a long closed state. It's like a long closed solenoid valve. This way, in a real-time painting workflow or other workflows, you can allow subsequent workflows to take effect at the touch of a button, without having to switch subsequent workflows on and off frequently.

I don't know if this node can be realized inside comfyui, my code level is limited, I wrote it in gpt for two days but I didn't understand it, please answer my questions.

**Comment by chrisgoringe** [comment]
Thanks for the idea... I'm not familiar with real time painting nodes. Does that mean the workflow runs continuously? Whenever you make a change to the painting the new version gets submitted?

If that is correct, I can imagine a very simple node which just does two things:

- normally, when it receives an input, it cancels the run
- it has a button which, when pressed, causes it to pass the next image it receives through instead

Have I understood?

**Comment by RexLeeGrey** [comment]
When painting in real time, Auto Queue in Extra Options is turned on, and it should be said that usually when it receives input, it does not transfer data, rather than canceling the run, because the real time painting workflow runs continuously.

All other understandings are correct.

**Comment by RexLeeGrey** [comment]
[workflow.json](https://github.com/chrisgoringe/cg-image-picker/files/14902693/workflow.json)
这边上传了一个简单的实时绘画工作流，如果将设想的节点放在VAE decode和save image之间，那么当在绘画窗口绘画并开启自动队列时，图像只会传输到预览窗口，当得到满意的图像之后，点击这个按钮，图像将会传递到save image，从而被保存。

**Comment by chrisgoringe** [comment]
OK, I've made a node :). [Take a look](https://github.com/chrisgoringe/cg-simple-gate) and see if it does what you are after.

**Comment by RexLeeGrey** [comment]
Very impressive work! This was able to get the live drawing workflow on comfyui to work perfectly and switch more cleanly.

However, with the nodes blinking constantly and the buttons being unintuitive when running, I was wondering if it would be possible to make a button like the one below so that it could control the opening and closing of the gate. For example, using the gate as an input and connecting the button to it would allow you to switch states by clicking on it. And after miniaturizing or moving the node farther away, the blinking wouldn't affect the creator too much.
![image](https://github.com/chrisgoringe/cg-image-picker/assets/125941057/9e2f2223-f48f-4e5b-a35b-fee49a872adc)
![image](https://github.com/chrisgoringe/cg-image-picker/assets/125941057/93e34b10-f437-41e1-8c81-261c3e2d3df6)
![image](https://github.com/chrisgoringe/cg-image-picker/assets/125941057/7a23071a-d85e-4901-83db-1a384664c77f)
![image](https://github.com/chrisgoringe/cg-image-picker/assets/125941057/531d4fb1-850a-41ac-8949-f67d2a929747)

**Comment by chrisgoringe** [comment]
I'll look at that. But for the blinking, try using the sleep option, set it to 2 or 3

**Comment by chrisgoringe** [comment]
Closing this - I've raised an issue on the simple gate repo - https://github.com/chrisgoringe/cg-simple-gate/issues/1
