### ISSUE TITLE
loop and can't output ?

### ISSUE THREAD

**Issue by K-O-N-B** [chrisgoringe/cg-image-picker#98]
![image](https://github.com/chrisgoringe/cg-image-picker/assets/152141077/20e290ee-ed31-4deb-b61d-220b5386b47d)

Hello there, this is my workflow, I use 2 samplers to gen different image, and use switcher to control the images and latent output.

but whatever I clicked which " progress selected image" button, that will re-start another ksampler to gen the image in loop. and can't start my flollowing upscale process.

last week, it's can slated by bypass one of the group (chooser), that's will continues the upscale process, but after I update the comfyui and node, didn't work again. 

How can I fix this and let the workflow can continues?

**Comment by chrisgoringe** [comment]
I'm sorry, I'm not understanding your description. Perhaps you could post the actual workflow (json file)?

**Comment by K-O-N-B** [comment]
okok


[000.json](https://github.com/chrisgoringe/cg-image-picker/files/14916412/000.json)


my goal is send the latent/image to upscale

**Comment by K-O-N-B** [comment]
I modify the workflow like this and fix the loop problem, anyway, thank you~!

and, could you tell me what is meaning "count" in your node? I can't find the answer in readme file.

![image](https://github.com/chrisgoringe/cg-image-picker/assets/152141077/a4be658f-e871-4b9b-996c-e40372e27f25)
