### ISSUE TITLE
Image Chooser, mask bug

### ISSUE THREAD

**Issue by lancje** [chrisgoringe/cg-image-picker#99]
While using the Image Chooser, I opened the mask editor to add a mask, but it was not successful. 
Upon previewing the mask image, I found that it did not appear in the subsequent step. Only when the image from the current step is passed to the Image Chooser along with the mask node, does the mask successfully transfer to the next step in the Image Chooser. This means that the mask editor inherent to the Image Chooser is ineffective.
     Certainly, all of my other nodes are correctly configured. In fact, my intention is to add a mask to an already generated image without the need to reload it and proceed with the redrawing work in the next step. For example, the Preview Bridge (Image) node within the Impact Pack can perform mask addition for the generated image, but the Preview Bridge (Image) does not provide a pause function. Therefore, I still hope that you can resolve the issue with the Image Chooser.

**Comment by chrisgoringe** [comment]
Image chooser is not designed to allow for mask editing, and this is not a feature I am likely to add

**Comment by lancje** [comment]
ok.ths，

**Comment by skywolf123** [comment]
> ok.ths，

Do you have any workaround to solve the problem?
